
default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  username: ebraheem
  password: hamed
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: basw_dev




